### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by jwood36** [joshSawYou/CIS255_Vehicle#1]
You need spend more time on documenting your inheritance structure in your UML File.

Your current Diagram doesnt say anything about your implementation for Task #2.  Its more of something I would put in slides.

Your UML diagram also represents Enums explicitly, which was not communicated and referred to multiple time in lectures to not represent them on their own.

It was also communicated that the entry class "CIS255_Vehicle" would not be represented in the Diagram.

**Comment by joshSawYou** [comment]
I have now provided much more detail for my UML file in the readme files per your request. 

My detailed explanation now further mirrors my implementation.

For task #2, Enums are now supposed to be in the UML,  just not have their own page, Correct?

I have now taken the entry class "CIS255_Vehicle"  out of the diagram.

**Comment by joshSawYou** [comment]
I have spent even further time on my UML and its documentation. I believe the UML design itself is organized, readable, and implementable. I also believe my documentation is thorough and explains the design in a detailed manner.
