### ISSUE TITLE
Abstraction - Inheritance

### ISSUE THREAD

**Issue by jwood36** [joshSawYou/CIS255_Vehicle#10]
Choose which one you are going to implement, Make or Type Abstraction

>  * Abstraction
>         * At least one (1) Abstract Class for each Make OR Type
>             > Follow Naming Convention

**Comment by joshSawYou** [comment]
I chose the make route. From here, there are model classes (FordModels, etc. which have their corresponding make-model classes inside of them (FordF150, etc.)
