### ISSUE TITLE
UML - Inheritance Model

### ISSUE THREAD

**Issue by jwood36** [joshSawYou/CIS255_Vehicle#3]
Choose which inheritance Model you will implement: (1) Make or (2) Type

Once you have decided with path you are going down, represent this in your UML Diagram with the appropriate Model associated.

Once that is done, identify how your "Root" object will look like and prepare for the Java class implementation

**Comment by joshSawYou** [comment]
I have chosen the "Make" inheritance Model I will implement.

I represented this in my UML Diagram with the appropriate Model associated.

I have identified how my "Root" object will look and prepareed for the Java class implementation.
