### ISSUE TITLE
UML - Abstraction

### ISSUE THREAD

**Issue by jwood36** [joshSawYou/CIS255_Vehicle#7]
Abstract your Model Classes into Categories and show Inheritance to those Categories.

Right now you have a "Lord of the Classes" model.  This is not efficient for support or resources.  One class failure in "Model" will cause all 25 of your Models to also fail.

In summary, avoid designing a UML where all your Eggs are in One Basket.  Currently your Basket is the Model Class, all of the Named Model Classes are solely dependent on that one class and it makes it harder to read.

**Comment by joshSawYou** [comment]
I have further separated the classes to avoid a UML design where all my Eggs are in One Basket. This way if there is a class failure it wont cause all other child classes to also fail. I did so by having make have child classes: FordModels, TeslaModels, ToyotaModels, DOdgeModels, and HondaModels and then the corresponding make-model combinations of individual vehicles belong to those classes. This provided a much more separated and organized uml structure; thus I believe this fixed my Lord of all classes problem.
